# https://taskfile.dev
version: '3'

dotenv: ['.env', '{{.HOME}}/.env']

tasks:
  default:
    desc: If running only "task" print all available tasks
    cmd: task --list-all
    silent: true

  brew:
    desc: Install tool dependencies with brew
    internal: true
    run: once
    platforms: [darwin, linux]
    cmd: brew bundle --no-lock --verbose
    status:
      - brew bundle check --verbose

  test:
    desc: Run tests
    run: once
    cmd: tilt ci -- --run-tests
