apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: cross-selling-ragas-evaluation
  namespace: testkube
  labels:
      {{ include "showcase-cross-selling.labels" . | nindent 4 }}
spec:
  content:
    files:
      - path: /data/datasets/experiment.json
        contentFrom:
          configMapKeyRef:
            name: experiments
            key: cross-selling-experiment.json

  container:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: otel-config
            key: OTEL_EXPORTER_OTLP_ENDPOINT

  use:
    - name: run-template
      config:
        agentUrl: "http://cross-selling-agent.showcase-cross-selling:8000"
    - name: evaluate-template
      config:
        openApiBasePath: "http://ai-gateway.ai-gateway:4000"
        model: "gemini-2.5-flash-lite"
    - name: publish-template
    - name: visualize-template