apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolServer
metadata:
  name: customer-crm
  namespace: {{ .Values.namespace.name }}
  labels:
    {{ include "showcase-cross-selling.labels" . | nindent 4 }}
spec:
  protocol: mcp
  transportType: http
  image: {{ .Values.images.toolServers.customerCrm.repository }}:{{ .Values.images.toolServers.customerCrm.tag }}
  args:
    - "customer_crm.py"
  port: 8000
  replicas: 1
  env:
    - name: OTEL_SERVICE_NAME
      value: customer-crm
    - name: LOGLEVEL
      value: {{ .Values.toolServers.logLevel | quote }}
  {{- with .Values.extraEnv }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolRoute
metadata:
  name: customer-crm
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{ include "showcase-cross-selling.labels" $ | nindent 4 }}
spec:
  {{- with .Values.toolGateway.ref }}
  toolGatewayRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  upstream:
    toolServerRef:
      name: customer-crm
