{{- if .Values.testbench.enabled }}
apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: insurance-host-ragas-evaluation
  namespace: testkube
  labels:
      {{ include "showcase-cross-selling.labels" . | nindent 4 }}
spec:
  content:
    files:
      - path: /data/datasets/experiment.json
        contentFrom:
          configMapKeyRef:
            name: datasets
            key: insurance-host-experiment.json

  container:
    {{- with .Values.testbench.extraEnv }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}

  use:
    - name: run-template
      config:
        agentUrl: "http://insurance-host-agent.showcase-cross-selling:8000"
    - name: evaluate-template
      config:
        openApiBasePath: "http://ai-gateway.ai-gateway"
        model: "gemini-2.5-flash-lite"
    - name: publish-template
    - name: visualize-template
{{- end }}
