apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolServer
metadata:
  name: customer-crm
spec:
  protocol: mcp
  transportType: http
  image: customer_crm:latest
  port: 8000
  replicas: 1
  env:
    - name: OTEL_SERVICE_NAME
      value: customer-crm-mcp
  envFrom:
    - configMapRef:
        name: otel-tempo-config
        optional: true